<?php

namespace Database\Seeders;

use App\Models\BoilerBrand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BoilerBrandsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        BoilerBrand::insert([
            ['name' => 'ACV', 'created_at' => date("Y-m-d", time())],
            ['name' => 'AEG', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ALPHA', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ARISTON', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ATAG', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ATMOS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Baumatic', 'created_at' => date("Y-m-d", time())],
            ['name' => 'BAXI', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Beko', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Bexel', 'created_at' => date("Y-m-d", time())],
            ['name' => 'BIASI', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Bosch', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Brandt', 'created_at' => date("Y-m-d", time())],
            ['name' => 'BRITISH GAS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'BUDERUS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Bush', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Candy', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Cannon', 'created_at' => date("Y-m-d", time())],
            ['name' => 'CDA', 'created_at' => date("Y-m-d", time())],
            ['name' => 'CHAFFOTEAUX', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Cucina', 'created_at' => date("Y-m-d", time())],
            ['name' => 'DAIKIN', 'created_at' => date("Y-m-d", time())],
            ['name' => 'DAXOM', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Delonghi', 'created_at' => date("Y-m-d", time())],
            ['name' => 'DIMPLEX', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Diplomat', 'created_at' => date("Y-m-d", time())],
            ['name' => 'E H C', 'created_at' => date("Y-m-d", time())],
            ['name' => 'E.C.A.', 'created_at' => date("Y-m-d", time())],
            ['name' => 'E.L.M. LEBLANC', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ECOHOMETEC', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ELCO', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Electra', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Electrolux', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ELNUR', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Essentials', 'created_at' => date("Y-m-d", time())],
            ['name' => 'EVINOX', 'created_at' => date("Y-m-d", time())],
            ['name' => 'FERROLI', 'created_at' => date("Y-m-d", time())],
            ['name' => 'FIAMMA GIRO', 'created_at' => date("Y-m-d", time())],
            ['name' => 'FIREBIRD', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Flavel', 'created_at' => date("Y-m-d", time())],
            ['name' => 'FONDITAL', 'created_at' => date("Y-m-d", time())],
            ['name' => 'GEMINOX', 'created_at' => date("Y-m-d", time())],
            ['name' => 'GERKROS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'GLOWWORM', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Gorenje', 'created_at' => date("Y-m-d", time())],
            ['name' => 'GRANDEE', 'created_at' => date("Y-m-d", time())],
            ['name' => 'GRANT', 'created_at' => date("Y-m-d", time())],
            ['name' => 'HALSTEAD', 'created_at' => date("Y-m-d", time())],
            ['name' => 'HAMWORTHY', 'created_at' => date("Y-m-d", time())],
            ['name' => 'HEAT LINE', 'created_at' => date("Y-m-d", time())],
            ['name' => 'HERMANN', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Homark', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Hoover', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Hot point', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Hotpoint', 'created_at' => date("Y-m-d", time())],
            ['name' => 'IDEAL', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Ignis', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Ikea', 'created_at' => date("Y-m-d", time())],
            ['name' => 'IMMERGAS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Indesit', 'created_at' => date("Y-m-d", time())],
            ['name' => 'INTERGAS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'JAGUAR', 'created_at' => date("Y-m-d", time())],
            ['name' => 'JOHNSON STARLEY', 'created_at' => date("Y-m-d", time())],
            ['name' => 'JUNKERS BOSCH', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Kenwood', 'created_at' => date("Y-m-d", time())],
            ['name' => 'KESTON', 'created_at' => date("Y-m-d", time())],
            ['name' => 'LAARS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Lamona', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Leisure', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Logik', 'created_at' => date("Y-m-d", time())],
            ['name' => 'M H G', 'created_at' => date("Y-m-d", time())],
            ['name' => 'M H S', 'created_at' => date("Y-m-d", time())],
            ['name' => 'MAIN', 'created_at' => date("Y-m-d", time())],
            ['name' => 'MALVERN', 'created_at' => date("Y-m-d", time())],
            ['name' => 'MAXOL', 'created_at' => date("Y-m-d", time())],
            ['name' => 'MIKROFILL', 'created_at' => date("Y-m-d", time())],
            ['name' => 'MIZUDO', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Moffat', 'created_at' => date("Y-m-d", time())],
            ['name' => 'MORCO', 'created_at' => date("Y-m-d", time())],
            ['name' => 'MYSON', 'created_at' => date("Y-m-d", time())],
            ['name' => 'NAVIEN', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Neff', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Neue', 'created_at' => date("Y-m-d", time())],
            ['name' => 'New world', 'created_at' => date("Y-m-d", time())],
            ['name' => 'POTTERTON', 'created_at' => date("Y-m-d", time())],
            ['name' => 'PROCOMBI', 'created_at' => date("Y-m-d", time())],
            ['name' => 'PROTHERM', 'created_at' => date("Y-m-d", time())],
            ['name' => 'RADIANT', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Rangemaster', 'created_at' => date("Y-m-d", time())],
            ['name' => 'RAVENHEAT', 'created_at' => date("Y-m-d", time())],
            ['name' => 'REMEHA', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ROC', 'created_at' => date("Y-m-d", time())],
            ['name' => 'SAUNIER DUVAL', 'created_at' => date("Y-m-d", time())],
            ['name' => 'SAVIO', 'created_at' => date("Y-m-d", time())],
            ['name' => 'SERVOWARM', 'created_at' => date("Y-m-d", time())],
            ['name' => 'SIME', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Smeg', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Statesman', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Stoves', 'created_at' => date("Y-m-d", time())],
            ['name' => 'STREBEL', 'created_at' => date("Y-m-d", time())],
            ['name' => 'THERMAFLOW', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Tricity Bendix', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Unknown', 'created_at' => date("Y-m-d", time())],
            ['name' => 'VAILLANT', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Vaxi', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Victoriana', 'created_at' => date("Y-m-d", time())],
            ['name' => 'VIESSMANN', 'created_at' => date("Y-m-d", time())],
            ['name' => 'VOKERA', 'created_at' => date("Y-m-d", time())],
            ['name' => 'WARMFLOW', 'created_at' => date("Y-m-d", time())],
            ['name' => 'WARMHAUS', 'created_at' => date("Y-m-d", time())],
            ['name' => 'WEIL MCLAIN', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Whirlpool', 'created_at' => date("Y-m-d", time())],
            ['name' => 'WORCESTER', 'created_at' => date("Y-m-d", time())],
            ['name' => 'Worcester bosch', 'created_at' => date("Y-m-d", time())],
            ['name' => 'ZANUSSI', 'created_at' => date("Y-m-d", time())],
        ]);
    }
}
